// File generated by FlutterFire CLI or placeholder configuration for showscape-784a9.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyShowScapeMockApiKeyForWebConfig12345',
    appId: '1:100000000000:web:showscape784a9web',
    messagingSenderId: '100000000000',
    projectId: 'showscape-784a9',
    authDomain: 'showscape-784a9.firebaseapp.com',
    storageBucket: 'showscape-784a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyShowScapeMockApiKeyForAndroidConfig123',
    appId: '1:100000000000:android:showscape784a9android',
    messagingSenderId: '100000000000',
    projectId: 'showscape-784a9',
    storageBucket: 'showscape-784a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyShowScapeMockApiKeyForIOSConfig1234567',
    appId: '1:100000000000:ios:showscape784a9ios',
    messagingSenderId: '100000000000',
    projectId: 'showscape-784a9',
    storageBucket: 'showscape-784a9.firebasestorage.app',
    iosBundleId: 'com.example.showscape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyShowScapeMockApiKeyForMacOSConfig12345',
    appId: '1:100000000000:ios:showscape784a9macos',
    messagingSenderId: '100000000000',
    projectId: 'showscape-784a9',
    storageBucket: 'showscape-784a9.firebasestorage.app',
    iosBundleId: 'com.example.showscape.RunnerTests',
  );
}
