// File generated by FlutterFire CLI & configured for showscape-784a9.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnsuWx7wvoxKyY36iHBPm8VHeY3UbIanI',
    appId: '1:908151646783:web:213f8880e60689ff1ba68a',
    messagingSenderId: '908151646783',
    projectId: 'showscape-784a9',
    authDomain: 'showscape-784a9.firebaseapp.com',
    storageBucket: 'showscape-784a9.firebasestorage.app',
    measurementId: 'G-8SH16Y7ZP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn5nNw3Mo5VFeJqxwhxPyomY-mJdnLsRc',
    appId: '1:908151646783:android:044d97ca1ac202bd1ba68a',
    messagingSenderId: '908151646783',
    projectId: 'showscape-784a9',
    storageBucket: 'showscape-784a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn5sihCJI1a5nGq5SeU3TNKdNLbRZZN_U',
    appId: '1:908151646783:ios:7c8f8296db8156c91ba68a',
    messagingSenderId: '908151646783',
    projectId: 'showscape-784a9',
    storageBucket: 'showscape-784a9.firebasestorage.app',
    iosBundleId: 'com.showscape.showscape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn5sihCJI1a5nGq5SeU3TNKdNLbRZZN_U',
    appId: '1:908151646783:ios:7c8f8296db8156c91ba68a',
    messagingSenderId: '908151646783',
    projectId: 'showscape-784a9',
    storageBucket: 'showscape-784a9.firebasestorage.app',
    iosBundleId: 'com.showscape.showscape',
  );
}
